name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Create a classic PAT and store as METRICS_TOKEN secret:
          # scopes: public_repo, read:user, read:org
          token: ${{ secrets.METRICS_TOKEN }}
          user: kavindus0
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          config_display: large

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_achievements: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_lines: yes

          # Output in repo root as metrics.svg (referenced by README)
          filename: metrics.svg

      - name: Commit updated metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update profile metrics [skip ci]"
          git push
